package algomusic_berwin_class;

import com.jsyn.data.SegmentedEnvelope;
import com.jsyn.ports.UnitInputPort;

/**************
** WARNING - this code automatically generated by Syntona.
** The real source is probably a Syntona patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Syntona.
**
** Syntona is available from: http://www.softsynth.com/syntona/
*/

import com.jsyn.ports.UnitOutputPort;
import com.jsyn.unitgen.Circuit;
import com.jsyn.unitgen.PassThrough;
import com.jsyn.unitgen.SquareOscillator;
import com.jsyn.unitgen.UnitVoice;
import com.jsyn.unitgen.VariableRateMonoReader;
import com.softsynth.shared.time.TimeStamp;

public class Sawvoice extends Circuit implements UnitVoice {
    // Declare units and ports.
    PassThrough mFrequencyPassThrough;
    public UnitInputPort frequency;
    PassThrough mAmplitudePassThrough;
    public UnitInputPort amplitude;
    PassThrough mOutputPassThrough;
    public UnitOutputPort output;
    SquareOscillator mSquareOsc;
    VariableRateMonoReader mMonoRdr;
    SegmentedEnvelope mSegEnv;

    // Declare inner classes for any child circuits.

    public Sawvoice() {
        // Create unit generators.
        add(mFrequencyPassThrough = new PassThrough());
        addPort(frequency = mFrequencyPassThrough.input, "frequency");
        add(mAmplitudePassThrough = new PassThrough());
        addPort(amplitude = mAmplitudePassThrough.input, "amplitude");
        add(mOutputPassThrough = new PassThrough());
        addPort( output = mOutputPassThrough.output, "output");
        add(mSquareOsc = new SquareOscillator());
        add(mMonoRdr = new VariableRateMonoReader());
        double[] mSegEnvData = {
            0.5, 1.0,
            0.10593785005559875, 0.3201754385964912,
            0.1451656662941101, 0.24561403508771928,
            0.5, 0.0,
        };
        mSegEnv = new SegmentedEnvelope( mSegEnvData );
        // Connect units and ports.
        mFrequencyPassThrough.output.connect(mSquareOsc.frequency);
        mAmplitudePassThrough.output.connect(mMonoRdr.amplitude);
        mSquareOsc.output.connect(mOutputPassThrough.input);
        mMonoRdr.output.connect(mSquareOsc.amplitude);
        // Setup
        frequency.setup(40.0, 329.6275569128699, 8000.0);
        amplitude.setup(0.0, 0.5, 1.0);
        mMonoRdr.rate.set(1.0);
    }

    public void noteOn(double frequency, double amplitude, TimeStamp timeStamp) {
        this.frequency.set(frequency, timeStamp);
        this.amplitude.set(amplitude, timeStamp);
        mMonoRdr.dataQueue.queueOn( mSegEnv, timeStamp);
    }

    public void noteOff(TimeStamp timeStamp) {
        mMonoRdr.dataQueue.queueOff( mSegEnv, false, timeStamp);
    }
    
    public UnitOutputPort getOutput() {
        return output;
    }
}
