package algomusic_berwin_class;

/**************
** WARNING - this code automatically generated by Syntona.
** The real source is probably a Syntona patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Syntona.
**
** Syntona is available from: http://www.softsynth.com/syntona/
*/

import com.jsyn.ports.UnitOutputPort;
import com.jsyn.unitgen.UnitVoice;
import com.jsyn.unitgen.VariableRateMonoReader;
import com.jsyn.unitgen.Add;
import com.jsyn.ports.UnitInputPort;
import com.jsyn.unitgen.Multiply;
import com.jsyn.unitgen.SineOscillator;
import com.softsynth.shared.time.TimeStamp;
import com.jsyn.unitgen.PassThrough;
import com.jsyn.data.SegmentedEnvelope;
import com.jsyn.unitgen.Circuit;

public class Test2 extends Circuit implements UnitVoice {
    // Declare units and ports.
    PassThrough mFrequencyPassThrough;
    public UnitInputPort frequency;
    PassThrough mAmplitudePassThrough;
    public UnitInputPort amplitude;
    PassThrough mOutputPassThrough;
    public UnitOutputPort output;
    SineOscillator mSineOsc;
    SegmentedEnvelope mSegEnv;
    VariableRateMonoReader mMonoRdr;
    SineOscillator mSineOsc2;
    Multiply mAtimes;
    Add mAplus;
    Multiply mAtimes2;
    SineOscillator mSineOsc3;
    Add mAplus2;

    // Declare inner classes for any child circuits.

    public Test2() {
        // Create unit generators.
        add(mFrequencyPassThrough = new PassThrough());
        addPort(frequency = mFrequencyPassThrough.input, "frequency");
        add(mAmplitudePassThrough = new PassThrough());
        addPort(amplitude = mAmplitudePassThrough.input, "amplitude");
        add(mOutputPassThrough = new PassThrough());
        addPort( output = mOutputPassThrough.output, "output");
        add(mSineOsc = new SineOscillator());
        double[] mSegEnvData = {
            0.5, 1.0,
            0.5, 0.2,
            0.5, 0.8,
            0.5, 0.0,
        };
        mSegEnv = new SegmentedEnvelope( mSegEnvData );
        add(mMonoRdr = new VariableRateMonoReader());
        add(mSineOsc2 = new SineOscillator());
        add(mAtimes = new Multiply());
        add(mAplus = new Add());
        add(mAtimes2 = new Multiply());
        add(mSineOsc3 = new SineOscillator());
        add(mAplus2 = new Add());
        // Connect units and ports.
        mFrequencyPassThrough.output.connect(mSineOsc.frequency);
        mFrequencyPassThrough.output.connect(mAtimes.inputA);
        mFrequencyPassThrough.output.connect(mAtimes2.inputA);
        mAmplitudePassThrough.output.connect(mMonoRdr.amplitude);
        mSineOsc.output.connect(mAplus.inputA);
        mMonoRdr.output.connect(mSineOsc.amplitude);
        mMonoRdr.output.connect(mSineOsc2.amplitude);
        mMonoRdr.output.connect(mSineOsc3.amplitude);
        mSineOsc2.output.connect(mAplus.inputB);
        mAtimes.output.connect(mSineOsc2.frequency);
        mAplus.output.connect(mAplus2.inputA);
        mAtimes2.output.connect(mSineOsc3.frequency);
        mSineOsc3.output.connect(mAplus2.inputB);
        mAplus2.output.connect(mOutputPassThrough.input);
        // Setup
        frequency.setup(40.0, 440.0, 8000.0);
        amplitude.setup(0.0, 1.0, 1.0);
        mMonoRdr.rate.set(1.0);
        mAtimes.inputB.set(0.8);
        mAtimes2.inputB.set(0.66);
    }

    public void noteOn(double frequency, double amplitude, TimeStamp timeStamp) {
        this.frequency.set(frequency, timeStamp);
        this.amplitude.set(amplitude, timeStamp);
        mMonoRdr.dataQueue.queueOn( mSegEnv, timeStamp);
    }

    public void noteOff(TimeStamp timeStamp) {
        mMonoRdr.dataQueue.queueOff( mSegEnv, false, timeStamp);
    }
    
    public UnitOutputPort getOutput() {
        return output;
    }
}
